name: Perl6-Doc
version: 0.33
abstract: all useful Perl 6 Docs in your command line
author: lichtkind@cpan.org
license: perl
distribution_type: module
generated_by: Module::Install version 0.57
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.000
