---
abstract: 'Perl 6 documentation'
author:
  - 'Hinrik Örn Sigurðsson <hinrik.sig@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.102400'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Perl6-Doc
no_index:
  directory:
    - utils
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Perl6-Doc
  homepage: http://search.cpan.org/dist/Perl6-Doc
  repository: git://github.com/hinrik/perl6-doc.git
version: 0.46
x_authority: cpan:HINRIK
